include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Modern best practices
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - use_super_parameters
    - unnecessary_null_checks
    - use_colored_box
    - use_decorated_box

    # Style
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - curly_braces_in_flow_control_structures

    # Documentation
    - package_api_docs
    - public_member_api_docs

    # Error handling
    - use_rethrow_when_possible
    - avoid_catches_without_on_clauses

    # Functional
    - prefer_collection_literals
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - prefer_typing_uninitialized_variables
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions
    - avoid_positional_boolean_parameters
    - hash_and_equals
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - use_setters_to_change_properties
    - avoid_setters_without_getters
