name: blobs
description: Create beautiful blobs - fixed/random blob generation, animations, svgs and more
version: 3.0.0
homepage: https://github.com/lokesh-coder/flutter_blobs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
